### ISSUE TITLE
点点券PTPIN无法解析的bug

### ISSUE THREAD

**Issue by liaopen123** [colakele/jd#2]
pt_key=xxxxxxxxxxxxxxxxxxxxxx;pt_pin=14969-8440152;情况的时候 会报错
点点券, 错误!
TypeError: Cannot read property '1' of null
    at ZooFakerNecklace.run (/ql/scripts/colakele_jd_jd_necklace.js:58:47)
    at async getBody (/ql/scripts/colakele_jd_jd_necklace.js:186:17)
    at async doTask (/ql/scripts/colakele_jd_jd_necklace.js:271:16)
    at async jd_necklace (/ql/scripts/colakele_jd_jd_necklace.js:241:5)
    at async /ql/scripts/colakele_jd_jd_necklace.js:225:7

**Comment by colakele** [comment]
已更新
